title: 東京大学薫風流煎茶同好会
description: 東京大学で活動するサークル「薫風流煎茶同好会」の公式サイトです。急須で淹れる「煎茶道」を学んでみませんか？玉露の味わいや、四季折々のお茶を楽しみながら、楽しくお稽古に励んでいます。
url: "https://sencha-ut.com" # ※実際の公開URLに変更してください
baseurl: "" 
lang: ja
author:
  name: 東京大学薫風流煎茶同好会
  twitter: sencha_ut
logo: "/assets/images/logos/doukoukai_logo_nobg.png"
image: "/assets/images/slide/slide01.jpg"
email: "sencha.shinkan@gmail.com"
twitter:
  username: sencha_ut
  card: summary_large_image
social:
  name: 東京大学薫風流煎茶同好会
  links:
    - https://twitter.com/sencha_ut
    - https://instagram.com/sencha_ut
recruitment:
  title: "新歓情報（26年度）"
  summary: "当同好会はサークルオリエンテーション(4/3(金)、4/5(日))に参加します。"
  details: "サークルオリエンテーションでは春ならではの桜茶を提供する予定ですので、ぜひお越しください！"
  form_label: "見学希望フォーム(26年度版)"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: sencha_ut
formurl: "https://forms.gle/eUJz89aFUpFzQWmS8"
theme: minima
plugins:
  - jekyll-seo-tag